-- MySQL Script generated by MySQL Workbench
-- Thu Jan 29 17:38:50 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema materias
-- -----------------------------------------------------
-- Esquema de base de datos para crear materias con sus profesores y estudiantes

-- -----------------------------------------------------
-- Schema materias
--
-- Esquema de base de datos para crear materias con sus profesores y estudiantes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `materias` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `materias` ;

-- -----------------------------------------------------
-- Table `persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `persona` ;

CREATE TABLE IF NOT EXISTS `persona` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(45) NOT NULL,
  `name` VARCHAR(125) NOT NULL,
  `tipo_persona` ENUM("V", "E") NULL,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asignatura` ;

CREATE TABLE IF NOT EXISTS `asignatura` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre_asignatura` VARCHAR(100) NOT NULL,
  `creditos` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estudiantes_inscritos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estudiantes_inscritos` ;

CREATE TABLE IF NOT EXISTS `estudiantes_inscritos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `persona_id` INT NOT NULL COMMENT 'id de los datos personales del estudiante',
  `asignatura_id` INT NOT NULL COMMENT 'id de la asignatura inscrita por el estudiante',
  `fecha_inscripcion` DATE NOT NULL COMMENT 'fecha en la cual fue inscrito el estudiante',
  PRIMARY KEY (`id`),
  INDEX `fk_estudiantes_inscritos_persona_idx` (`persona_id` ASC) VISIBLE,
  INDEX `fk_estudiantes_inscritos_asignatura1_idx` (`asignatura_id` ASC) VISIBLE,
  CONSTRAINT `fk_estudiantes_inscritos_persona`
    FOREIGN KEY (`persona_id`)
    REFERENCES `persona` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estudiantes_inscritos_asignatura1`
    FOREIGN KEY (`asignatura_id`)
    REFERENCES `asignatura` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

